### ISSUE TITLE
controller

### ISSUE THREAD

**Issue by AMNESlA** [datdescartes/flutter_colorful_tab#1]
how do i begin the program with the tab in the middle ?

**Comment by datvu7** [comment]
Not related to my lib, but you can set the initial tab when initializing tabController like this
```
_tabController = new TabController(length: 5, vsync: this, initialIndex: 2);
```
Ref. https://github.com/datdescartes/flutter_colorful_tab/blob/5d9fd1504ddf84e341ef9384a663537b4b15c012/example/lib/main.dart#L36
